### ISSUE TITLE
still had to install the package sp

### ISSUE THREAD

**Issue by mgehling** [mpadge/osmplotr#11]
> dat_B <- extract_osm_objects (key='building', bbox=bbox)
> Loading required package: sp
> 
> install.packages ('sp')

**Comment by mpadge** [comment]
That's because `osmar` doesn't specify the dependency properly. `osmar` DESCRIPTION has

>  Suggests:
>    sp (>= 0.9-93)

and it should be under `Depends` not `Suggests` because `osmar::as-osmar-sp.R` has:

> as_osmar_bbox.Spatial <- function(obj, ...) {
>     stopifnot(require("sp"))
>      bb <- sp::bbox(obj)

That's a very unorthodox way to call a dependency. Annoying in `osmplotr` at present, but will be fixed when I replace `osmar` dependency with `osmdatar`. Until then, we'll have to live with it
